// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ClosePunctuation code points.

lo: u21 = 41,
hi: u21 = 65379,

const ClosePunctuation = @This();

pub fn isClosePunctuation(self: ClosePunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 41) return true;
    if (cp == 93) return true;
    if (cp == 125) return true;
    if (cp == 3899) return true;
    if (cp == 3901) return true;
    if (cp == 5788) return true;
    if (cp == 8262) return true;
    if (cp == 8318) return true;
    if (cp == 8334) return true;
    if (cp == 8969) return true;
    if (cp == 8971) return true;
    if (cp == 9002) return true;
    if (cp == 10089) return true;
    if (cp == 10091) return true;
    if (cp == 10093) return true;
    if (cp == 10095) return true;
    if (cp == 10097) return true;
    if (cp == 10099) return true;
    if (cp == 10101) return true;
    if (cp == 10182) return true;
    if (cp == 10215) return true;
    if (cp == 10217) return true;
    if (cp == 10219) return true;
    if (cp == 10221) return true;
    if (cp == 10223) return true;
    if (cp == 10628) return true;
    if (cp == 10630) return true;
    if (cp == 10632) return true;
    if (cp == 10634) return true;
    if (cp == 10636) return true;
    if (cp == 10638) return true;
    if (cp == 10640) return true;
    if (cp == 10642) return true;
    if (cp == 10644) return true;
    if (cp == 10646) return true;
    if (cp == 10648) return true;
    if (cp == 10713) return true;
    if (cp == 10715) return true;
    if (cp == 10749) return true;
    if (cp == 11811) return true;
    if (cp == 11813) return true;
    if (cp == 11815) return true;
    if (cp == 11817) return true;
    if (cp == 12297) return true;
    if (cp == 12299) return true;
    if (cp == 12301) return true;
    if (cp == 12303) return true;
    if (cp == 12305) return true;
    if (cp == 12309) return true;
    if (cp == 12311) return true;
    if (cp == 12313) return true;
    if (cp == 12315) return true;
    if (cp >= 12318 and cp <= 12319) return true;
    if (cp == 64830) return true;
    if (cp == 65048) return true;
    if (cp == 65078) return true;
    if (cp == 65080) return true;
    if (cp == 65082) return true;
    if (cp == 65084) return true;
    if (cp == 65086) return true;
    if (cp == 65088) return true;
    if (cp == 65090) return true;
    if (cp == 65092) return true;
    if (cp == 65096) return true;
    if (cp == 65114) return true;
    if (cp == 65116) return true;
    if (cp == 65118) return true;
    if (cp == 65289) return true;
    if (cp == 65341) return true;
    if (cp == 65373) return true;
    if (cp == 65376) return true;
    if (cp == 65379) return true;
    return false;
}