// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ConnectorPunctuation code points.

lo: u21 = 95,
hi: u21 = 65343,

const ConnectorPunctuation = @This();

pub fn isConnectorPunctuation(self: ConnectorPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 95) return true;
    if (cp >= 8255 and cp <= 8256) return true;
    if (cp == 8276) return true;
    if (cp >= 65075 and cp <= 65076) return true;
    if (cp >= 65101 and cp <= 65103) return true;
    if (cp == 65343) return true;
    return false;
}