// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CurrencySymbol code points.

lo: u21 = 36,
hi: u21 = 126128,

const CurrencySymbol = @This();

pub fn isCurrencySymbol(self: CurrencySymbol, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 36) return true;
    if (cp >= 162 and cp <= 165) return true;
    if (cp == 1423) return true;
    if (cp == 1547) return true;
    if (cp >= 2046 and cp <= 2047) return true;
    if (cp >= 2546 and cp <= 2547) return true;
    if (cp == 2555) return true;
    if (cp == 2801) return true;
    if (cp == 3065) return true;
    if (cp == 3647) return true;
    if (cp == 6107) return true;
    if (cp >= 8352 and cp <= 8383) return true;
    if (cp == 43064) return true;
    if (cp == 65020) return true;
    if (cp == 65129) return true;
    if (cp == 65284) return true;
    if (cp >= 65504 and cp <= 65505) return true;
    if (cp >= 65509 and cp <= 65510) return true;
    if (cp >= 73693 and cp <= 73696) return true;
    if (cp == 123647) return true;
    if (cp == 126128) return true;
    return false;
}