// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode EnclosingMark code points.

lo: u21 = 1160,
hi: u21 = 42610,

const EnclosingMark = @This();

pub fn isEnclosingMark(self: EnclosingMark, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 1160 and cp <= 1161) return true;
    if (cp == 6846) return true;
    if (cp >= 8413 and cp <= 8416) return true;
    if (cp >= 8418 and cp <= 8420) return true;
    if (cp >= 42608 and cp <= 42610) return true;
    return false;
}