// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Format code points.

lo: u21 = 173,
hi: u21 = 917631,

const Format = @This();

pub fn isFormat(self: Format, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 173) return true;
    if (cp >= 1536 and cp <= 1541) return true;
    if (cp == 1564) return true;
    if (cp == 1757) return true;
    if (cp == 1807) return true;
    if (cp == 2274) return true;
    if (cp == 6158) return true;
    if (cp >= 8203 and cp <= 8207) return true;
    if (cp >= 8234 and cp <= 8238) return true;
    if (cp >= 8288 and cp <= 8292) return true;
    if (cp >= 8294 and cp <= 8303) return true;
    if (cp == 65279) return true;
    if (cp >= 65529 and cp <= 65531) return true;
    if (cp == 69821) return true;
    if (cp == 69837) return true;
    if (cp >= 78896 and cp <= 78904) return true;
    if (cp >= 113824 and cp <= 113827) return true;
    if (cp >= 119155 and cp <= 119162) return true;
    if (cp == 917505) return true;
    if (cp >= 917536 and cp <= 917631) return true;
    return false;
}