// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode LetterNumber code points.

lo: u21 = 5870,
hi: u21 = 74862,

const LetterNumber = @This();

pub fn isLetterNumber(self: LetterNumber, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 5870 and cp <= 5872) return true;
    if (cp >= 8544 and cp <= 8578) return true;
    if (cp >= 8581 and cp <= 8584) return true;
    if (cp == 12295) return true;
    if (cp >= 12321 and cp <= 12329) return true;
    if (cp >= 12344 and cp <= 12346) return true;
    if (cp >= 42726 and cp <= 42735) return true;
    if (cp >= 65856 and cp <= 65908) return true;
    if (cp == 66369) return true;
    if (cp == 66378) return true;
    if (cp >= 66513 and cp <= 66517) return true;
    if (cp >= 74752 and cp <= 74862) return true;
    return false;
}