// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode LineSeparator code points.

lo: u21 = 8232,
hi: u21 = 8232,

const LineSeparator = @This();

pub fn isLineSeparator(self: LineSeparator, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 8232) return true;
    return false;
}