// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ModifierSymbol code points.

lo: u21 = 94,
hi: u21 = 127999,

const ModifierSymbol = @This();

pub fn isModifierSymbol(self: ModifierSymbol, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 94) return true;
    if (cp == 96) return true;
    if (cp == 168) return true;
    if (cp == 175) return true;
    if (cp == 180) return true;
    if (cp == 184) return true;
    if (cp >= 706 and cp <= 709) return true;
    if (cp >= 722 and cp <= 735) return true;
    if (cp >= 741 and cp <= 747) return true;
    if (cp == 749) return true;
    if (cp >= 751 and cp <= 767) return true;
    if (cp == 885) return true;
    if (cp >= 900 and cp <= 901) return true;
    if (cp == 8125) return true;
    if (cp >= 8127 and cp <= 8129) return true;
    if (cp >= 8141 and cp <= 8143) return true;
    if (cp >= 8157 and cp <= 8159) return true;
    if (cp >= 8173 and cp <= 8175) return true;
    if (cp >= 8189 and cp <= 8190) return true;
    if (cp >= 12443 and cp <= 12444) return true;
    if (cp >= 42752 and cp <= 42774) return true;
    if (cp >= 42784 and cp <= 42785) return true;
    if (cp >= 42889 and cp <= 42890) return true;
    if (cp == 43867) return true;
    if (cp >= 43882 and cp <= 43883) return true;
    if (cp >= 64434 and cp <= 64449) return true;
    if (cp == 65342) return true;
    if (cp == 65344) return true;
    if (cp == 65507) return true;
    if (cp >= 127995 and cp <= 127999) return true;
    return false;
}