// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ModifierLetter code points.

lo: u21 = 688,
hi: u21 = 125259,

const ModifierLetter = @This();

pub fn isModifierLetter(self: ModifierLetter, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 688 and cp <= 705) return true;
    if (cp >= 710 and cp <= 721) return true;
    if (cp >= 736 and cp <= 740) return true;
    if (cp == 748) return true;
    if (cp == 750) return true;
    if (cp == 884) return true;
    if (cp == 890) return true;
    if (cp == 1369) return true;
    if (cp == 1600) return true;
    if (cp >= 1765 and cp <= 1766) return true;
    if (cp >= 2036 and cp <= 2037) return true;
    if (cp == 2042) return true;
    if (cp == 2074) return true;
    if (cp == 2084) return true;
    if (cp == 2088) return true;
    if (cp == 2417) return true;
    if (cp == 3654) return true;
    if (cp == 3782) return true;
    if (cp == 4348) return true;
    if (cp == 6103) return true;
    if (cp == 6211) return true;
    if (cp == 6823) return true;
    if (cp >= 7288 and cp <= 7293) return true;
    if (cp >= 7468 and cp <= 7530) return true;
    if (cp == 7544) return true;
    if (cp >= 7579 and cp <= 7615) return true;
    if (cp == 8305) return true;
    if (cp == 8319) return true;
    if (cp >= 8336 and cp <= 8348) return true;
    if (cp >= 11388 and cp <= 11389) return true;
    if (cp == 11631) return true;
    if (cp == 11823) return true;
    if (cp == 12293) return true;
    if (cp >= 12337 and cp <= 12341) return true;
    if (cp == 12347) return true;
    if (cp >= 12445 and cp <= 12446) return true;
    if (cp >= 12540 and cp <= 12542) return true;
    if (cp == 40981) return true;
    if (cp >= 42232 and cp <= 42237) return true;
    if (cp == 42508) return true;
    if (cp == 42623) return true;
    if (cp >= 42652 and cp <= 42653) return true;
    if (cp >= 42775 and cp <= 42783) return true;
    if (cp == 42864) return true;
    if (cp == 42888) return true;
    if (cp >= 43000 and cp <= 43001) return true;
    if (cp == 43471) return true;
    if (cp == 43494) return true;
    if (cp == 43632) return true;
    if (cp == 43741) return true;
    if (cp >= 43763 and cp <= 43764) return true;
    if (cp >= 43868 and cp <= 43871) return true;
    if (cp == 43881) return true;
    if (cp == 65392) return true;
    if (cp >= 65438 and cp <= 65439) return true;
    if (cp >= 92992 and cp <= 92995) return true;
    if (cp >= 94099 and cp <= 94111) return true;
    if (cp >= 94176 and cp <= 94177) return true;
    if (cp == 94179) return true;
    if (cp >= 123191 and cp <= 123197) return true;
    if (cp == 125259) return true;
    return false;
}