// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode OpenPunctuation code points.

lo: u21 = 40,
hi: u21 = 65378,

const OpenPunctuation = @This();

pub fn isOpenPunctuation(self: OpenPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 40) return true;
    if (cp == 91) return true;
    if (cp == 123) return true;
    if (cp == 3898) return true;
    if (cp == 3900) return true;
    if (cp == 5787) return true;
    if (cp == 8218) return true;
    if (cp == 8222) return true;
    if (cp == 8261) return true;
    if (cp == 8317) return true;
    if (cp == 8333) return true;
    if (cp == 8968) return true;
    if (cp == 8970) return true;
    if (cp == 9001) return true;
    if (cp == 10088) return true;
    if (cp == 10090) return true;
    if (cp == 10092) return true;
    if (cp == 10094) return true;
    if (cp == 10096) return true;
    if (cp == 10098) return true;
    if (cp == 10100) return true;
    if (cp == 10181) return true;
    if (cp == 10214) return true;
    if (cp == 10216) return true;
    if (cp == 10218) return true;
    if (cp == 10220) return true;
    if (cp == 10222) return true;
    if (cp == 10627) return true;
    if (cp == 10629) return true;
    if (cp == 10631) return true;
    if (cp == 10633) return true;
    if (cp == 10635) return true;
    if (cp == 10637) return true;
    if (cp == 10639) return true;
    if (cp == 10641) return true;
    if (cp == 10643) return true;
    if (cp == 10645) return true;
    if (cp == 10647) return true;
    if (cp == 10712) return true;
    if (cp == 10714) return true;
    if (cp == 10748) return true;
    if (cp == 11810) return true;
    if (cp == 11812) return true;
    if (cp == 11814) return true;
    if (cp == 11816) return true;
    if (cp == 11842) return true;
    if (cp == 12296) return true;
    if (cp == 12298) return true;
    if (cp == 12300) return true;
    if (cp == 12302) return true;
    if (cp == 12304) return true;
    if (cp == 12308) return true;
    if (cp == 12310) return true;
    if (cp == 12312) return true;
    if (cp == 12314) return true;
    if (cp == 12317) return true;
    if (cp == 64831) return true;
    if (cp == 65047) return true;
    if (cp == 65077) return true;
    if (cp == 65079) return true;
    if (cp == 65081) return true;
    if (cp == 65083) return true;
    if (cp == 65085) return true;
    if (cp == 65087) return true;
    if (cp == 65089) return true;
    if (cp == 65091) return true;
    if (cp == 65095) return true;
    if (cp == 65113) return true;
    if (cp == 65115) return true;
    if (cp == 65117) return true;
    if (cp == 65288) return true;
    if (cp == 65339) return true;
    if (cp == 65371) return true;
    if (cp == 65375) return true;
    if (cp == 65378) return true;
    return false;
}