// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode OtherNumber code points.

lo: u21 = 178,
hi: u21 = 127244,

const OtherNumber = @This();

pub fn isOtherNumber(self: OtherNumber, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 178 and cp <= 179) return true;
    if (cp == 185) return true;
    if (cp >= 188 and cp <= 190) return true;
    if (cp >= 2548 and cp <= 2553) return true;
    if (cp >= 2930 and cp <= 2935) return true;
    if (cp >= 3056 and cp <= 3058) return true;
    if (cp >= 3192 and cp <= 3198) return true;
    if (cp >= 3416 and cp <= 3422) return true;
    if (cp >= 3440 and cp <= 3448) return true;
    if (cp >= 3882 and cp <= 3891) return true;
    if (cp >= 4969 and cp <= 4988) return true;
    if (cp >= 6128 and cp <= 6137) return true;
    if (cp == 6618) return true;
    if (cp == 8304) return true;
    if (cp >= 8308 and cp <= 8313) return true;
    if (cp >= 8320 and cp <= 8329) return true;
    if (cp >= 8528 and cp <= 8543) return true;
    if (cp == 8585) return true;
    if (cp >= 9312 and cp <= 9371) return true;
    if (cp >= 9450 and cp <= 9471) return true;
    if (cp >= 10102 and cp <= 10131) return true;
    if (cp == 11517) return true;
    if (cp >= 12690 and cp <= 12693) return true;
    if (cp >= 12832 and cp <= 12841) return true;
    if (cp >= 12872 and cp <= 12879) return true;
    if (cp >= 12881 and cp <= 12895) return true;
    if (cp >= 12928 and cp <= 12937) return true;
    if (cp >= 12977 and cp <= 12991) return true;
    if (cp >= 43056 and cp <= 43061) return true;
    if (cp >= 65799 and cp <= 65843) return true;
    if (cp >= 65909 and cp <= 65912) return true;
    if (cp >= 65930 and cp <= 65931) return true;
    if (cp >= 66273 and cp <= 66299) return true;
    if (cp >= 66336 and cp <= 66339) return true;
    if (cp >= 67672 and cp <= 67679) return true;
    if (cp >= 67705 and cp <= 67711) return true;
    if (cp >= 67751 and cp <= 67759) return true;
    if (cp >= 67835 and cp <= 67839) return true;
    if (cp >= 67862 and cp <= 67867) return true;
    if (cp >= 68028 and cp <= 68029) return true;
    if (cp >= 68032 and cp <= 68047) return true;
    if (cp >= 68050 and cp <= 68095) return true;
    if (cp >= 68160 and cp <= 68168) return true;
    if (cp >= 68221 and cp <= 68222) return true;
    if (cp >= 68253 and cp <= 68255) return true;
    if (cp >= 68331 and cp <= 68335) return true;
    if (cp >= 68440 and cp <= 68447) return true;
    if (cp >= 68472 and cp <= 68479) return true;
    if (cp >= 68521 and cp <= 68527) return true;
    if (cp >= 68858 and cp <= 68863) return true;
    if (cp >= 69216 and cp <= 69246) return true;
    if (cp >= 69405 and cp <= 69414) return true;
    if (cp >= 69457 and cp <= 69460) return true;
    if (cp >= 69573 and cp <= 69579) return true;
    if (cp >= 69714 and cp <= 69733) return true;
    if (cp >= 70113 and cp <= 70132) return true;
    if (cp >= 71482 and cp <= 71483) return true;
    if (cp >= 71914 and cp <= 71922) return true;
    if (cp >= 72794 and cp <= 72812) return true;
    if (cp >= 73664 and cp <= 73684) return true;
    if (cp >= 93019 and cp <= 93025) return true;
    if (cp >= 93824 and cp <= 93846) return true;
    if (cp >= 119520 and cp <= 119539) return true;
    if (cp >= 119648 and cp <= 119672) return true;
    if (cp >= 125127 and cp <= 125135) return true;
    if (cp >= 126065 and cp <= 126123) return true;
    if (cp >= 126125 and cp <= 126127) return true;
    if (cp >= 126129 and cp <= 126132) return true;
    if (cp >= 126209 and cp <= 126253) return true;
    if (cp >= 126255 and cp <= 126269) return true;
    if (cp >= 127232 and cp <= 127244) return true;
    return false;
}