// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ParagraphSeparator code points.

lo: u21 = 8233,
hi: u21 = 8233,

const ParagraphSeparator = @This();

pub fn isParagraphSeparator(self: ParagraphSeparator, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 8233) return true;
    return false;
}