// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode PrivateUse code points.

lo: u21 = 57344,
hi: u21 = 1114109,

const PrivateUse = @This();

pub fn isPrivateUse(self: PrivateUse, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 57344 and cp <= 63743) return true;
    if (cp >= 983040 and cp <= 1048573) return true;
    if (cp >= 1048576 and cp <= 1114109) return true;
    return false;
}