// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Surrogate code points.

lo: u21 = 55296,
hi: u21 = 57343,

const Surrogate = @This();

pub fn isSurrogate(self: Surrogate, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 55296 and cp <= 57343) return true;
    return false;
}