// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode TitlecaseLetter code points.

lo: u21 = 453,
hi: u21 = 8188,

const TitlecaseLetter = @This();

pub fn isTitlecaseLetter(self: TitlecaseLetter, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 453) return true;
    if (cp == 456) return true;
    if (cp == 459) return true;
    if (cp == 498) return true;
    if (cp >= 8072 and cp <= 8079) return true;
    if (cp >= 8088 and cp <= 8095) return true;
    if (cp >= 8104 and cp <= 8111) return true;
    if (cp == 8124) return true;
    if (cp == 8140) return true;
    if (cp == 8188) return true;
    return false;
}