// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode EmojiModifierBase code points.

lo: u21 = 9757,
hi: u21 = 129501,

const EmojiModifierBase = @This();

pub fn isEmojiModifierBase(self: EmojiModifierBase, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 9757) return true;
    if (cp == 9977) return true;
    if (cp >= 9994 and cp <= 9996) return true;
    if (cp == 9997) return true;
    if (cp == 127877) return true;
    if (cp >= 127938 and cp <= 127940) return true;
    if (cp == 127943) return true;
    if (cp == 127946) return true;
    if (cp >= 127947 and cp <= 127948) return true;
    if (cp >= 128066 and cp <= 128067) return true;
    if (cp >= 128070 and cp <= 128080) return true;
    if (cp >= 128102 and cp <= 128107) return true;
    if (cp >= 128108 and cp <= 128109) return true;
    if (cp >= 128110 and cp <= 128120) return true;
    if (cp == 128124) return true;
    if (cp >= 128129 and cp <= 128131) return true;
    if (cp >= 128133 and cp <= 128135) return true;
    if (cp == 128143) return true;
    if (cp == 128145) return true;
    if (cp == 128170) return true;
    if (cp >= 128372 and cp <= 128373) return true;
    if (cp == 128378) return true;
    if (cp == 128400) return true;
    if (cp >= 128405 and cp <= 128406) return true;
    if (cp >= 128581 and cp <= 128583) return true;
    if (cp >= 128587 and cp <= 128591) return true;
    if (cp == 128675) return true;
    if (cp >= 128692 and cp <= 128693) return true;
    if (cp == 128694) return true;
    if (cp == 128704) return true;
    if (cp == 128716) return true;
    if (cp == 129292) return true;
    if (cp == 129295) return true;
    if (cp == 129304) return true;
    if (cp >= 129305 and cp <= 129310) return true;
    if (cp == 129311) return true;
    if (cp == 129318) return true;
    if (cp == 129328) return true;
    if (cp >= 129329 and cp <= 129330) return true;
    if (cp >= 129331 and cp <= 129337) return true;
    if (cp >= 129340 and cp <= 129342) return true;
    if (cp == 129399) return true;
    if (cp >= 129461 and cp <= 129462) return true;
    if (cp >= 129464 and cp <= 129465) return true;
    if (cp == 129467) return true;
    if (cp >= 129485 and cp <= 129487) return true;
    if (cp >= 129489 and cp <= 129501) return true;
    return false;
}