// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode EmojiComponent code points.

lo: u21 = 35,
hi: u21 = 917631,

const EmojiComponent = @This();

pub fn isEmojiComponent(self: EmojiComponent, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 35) return true;
    if (cp == 42) return true;
    if (cp >= 48 and cp <= 57) return true;
    if (cp == 8205) return true;
    if (cp == 8419) return true;
    if (cp == 65039) return true;
    if (cp >= 127462 and cp <= 127487) return true;
    if (cp >= 127995 and cp <= 127999) return true;
    if (cp >= 129456 and cp <= 129459) return true;
    if (cp >= 917536 and cp <= 917631) return true;
    return false;
}