// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Control code points.

lo: u21 = 0,
hi: u21 = 921599,

const Control = @This();

pub fn isControl(self: Control, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 0 and cp <= 9) return true;
    if (cp >= 11 and cp <= 12) return true;
    if (cp >= 14 and cp <= 31) return true;
    if (cp >= 127 and cp <= 159) return true;
    if (cp == 173) return true;
    if (cp == 1564) return true;
    if (cp == 6158) return true;
    if (cp == 8203) return true;
    if (cp >= 8206 and cp <= 8207) return true;
    if (cp == 8232) return true;
    if (cp == 8233) return true;
    if (cp >= 8234 and cp <= 8238) return true;
    if (cp >= 8288 and cp <= 8292) return true;
    if (cp == 8293) return true;
    if (cp >= 8294 and cp <= 8303) return true;
    if (cp == 65279) return true;
    if (cp >= 65520 and cp <= 65528) return true;
    if (cp >= 65529 and cp <= 65531) return true;
    if (cp >= 78896 and cp <= 78904) return true;
    if (cp >= 113824 and cp <= 113827) return true;
    if (cp >= 119155 and cp <= 119162) return true;
    if (cp == 917504) return true;
    if (cp == 917505) return true;
    if (cp >= 917506 and cp <= 917535) return true;
    if (cp >= 917632 and cp <= 917759) return true;
    if (cp >= 918000 and cp <= 921599) return true;
    return false;
}