// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode L code points.

lo: u21 = 4352,
hi: u21 = 43388,

const L = @This();

pub fn isL(self: L, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 4352 and cp <= 4447) return true;
    if (cp >= 43360 and cp <= 43388) return true;
    return false;
}