// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Prepend code points.

lo: u21 = 1536,
hi: u21 = 73030,

const Prepend = @This();

pub fn isPrepend(self: Prepend, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 1536 and cp <= 1541) return true;
    if (cp == 1757) return true;
    if (cp == 1807) return true;
    if (cp == 2274) return true;
    if (cp == 3406) return true;
    if (cp == 69821) return true;
    if (cp == 69837) return true;
    if (cp >= 70082 and cp <= 70083) return true;
    if (cp == 71999) return true;
    if (cp == 72001) return true;
    if (cp == 72250) return true;
    if (cp >= 72324 and cp <= 72329) return true;
    if (cp == 73030) return true;
    return false;
}