// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode RegionalIndicator code points.

lo: u21 = 127462,
hi: u21 = 127487,

const RegionalIndicator = @This();

pub fn isRegionalIndicator(self: RegionalIndicator, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 127462 and cp <= 127487) return true;
    return false;
}