// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode T code points.

lo: u21 = 4520,
hi: u21 = 55291,

const T = @This();

pub fn isT(self: T, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 4520 and cp <= 4607) return true;
    if (cp >= 55243 and cp <= 55291) return true;
    return false;
}