// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode V code points.

lo: u21 = 4448,
hi: u21 = 55238,

const V = @This();

pub fn isV(self: V, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 4448 and cp <= 4519) return true;
    if (cp >= 55216 and cp <= 55238) return true;
    return false;
}