// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode ZWJ code points.

lo: u21 = 8205,
hi: u21 = 8205,

const ZWJ = @This();

pub fn isZWJ(self: ZWJ, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 8205) return true;
    return false;
}