language: cpp
dist: bionic
services:
    - docker

before_install:
    # Install zig
    - sudo snap install zig --classic --edge

script:
    # Run tests
    - zig build test

after_success:
    - docker run --rm --security-opt seccomp=unconfined -v $(pwd):$(pwd) -w $(pwd) kcov/kcov kcov kcov-out ./zig-cache/o/*/test
    - bash <(curl -s https://codecov.io/bash) -s kcov-out
