// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode GraphemeLink code points.

lo: u21 = 2381,
hi: u21 = 73111,

const GraphemeLink = @This();

pub fn isGraphemeLink(self: GraphemeLink, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 2381) return true;
    if (cp == 2509) return true;
    if (cp == 2637) return true;
    if (cp == 2765) return true;
    if (cp == 2893) return true;
    if (cp == 3021) return true;
    if (cp == 3149) return true;
    if (cp == 3277) return true;
    if (cp >= 3387 and cp <= 3388) return true;
    if (cp == 3405) return true;
    if (cp == 3530) return true;
    if (cp == 3642) return true;
    if (cp == 3770) return true;
    if (cp == 3972) return true;
    if (cp >= 4153 and cp <= 4154) return true;
    if (cp == 5908) return true;
    if (cp == 5940) return true;
    if (cp == 6098) return true;
    if (cp == 6752) return true;
    if (cp == 6980) return true;
    if (cp == 7082) return true;
    if (cp == 7083) return true;
    if (cp >= 7154 and cp <= 7155) return true;
    if (cp == 11647) return true;
    if (cp == 43014) return true;
    if (cp == 43052) return true;
    if (cp == 43204) return true;
    if (cp == 43347) return true;
    if (cp == 43456) return true;
    if (cp == 43766) return true;
    if (cp == 44013) return true;
    if (cp == 68159) return true;
    if (cp == 69702) return true;
    if (cp == 69759) return true;
    if (cp == 69817) return true;
    if (cp >= 69939 and cp <= 69940) return true;
    if (cp == 70080) return true;
    if (cp == 70197) return true;
    if (cp == 70378) return true;
    if (cp == 70477) return true;
    if (cp == 70722) return true;
    if (cp == 70850) return true;
    if (cp == 71103) return true;
    if (cp == 71231) return true;
    if (cp == 71350) return true;
    if (cp == 71467) return true;
    if (cp == 71737) return true;
    if (cp == 71997) return true;
    if (cp == 71998) return true;
    if (cp == 72160) return true;
    if (cp == 72244) return true;
    if (cp == 72263) return true;
    if (cp == 72345) return true;
    if (cp == 72767) return true;
    if (cp >= 73028 and cp <= 73029) return true;
    if (cp == 73111) return true;
    return false;
}