// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Decimal code points.

lo: u21 = 48,
hi: u21 = 130041,

const Decimal = @This();

pub fn isDecimal(self: Decimal, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 48 and cp <= 57) return true;
    if (cp >= 1632 and cp <= 1641) return true;
    if (cp >= 1776 and cp <= 1785) return true;
    if (cp >= 1984 and cp <= 1993) return true;
    if (cp >= 2406 and cp <= 2415) return true;
    if (cp >= 2534 and cp <= 2543) return true;
    if (cp >= 2662 and cp <= 2671) return true;
    if (cp >= 2790 and cp <= 2799) return true;
    if (cp >= 2918 and cp <= 2927) return true;
    if (cp >= 3046 and cp <= 3055) return true;
    if (cp >= 3174 and cp <= 3183) return true;
    if (cp >= 3302 and cp <= 3311) return true;
    if (cp >= 3430 and cp <= 3439) return true;
    if (cp >= 3558 and cp <= 3567) return true;
    if (cp >= 3664 and cp <= 3673) return true;
    if (cp >= 3792 and cp <= 3801) return true;
    if (cp >= 3872 and cp <= 3881) return true;
    if (cp >= 4160 and cp <= 4169) return true;
    if (cp >= 4240 and cp <= 4249) return true;
    if (cp >= 6112 and cp <= 6121) return true;
    if (cp >= 6160 and cp <= 6169) return true;
    if (cp >= 6470 and cp <= 6479) return true;
    if (cp >= 6608 and cp <= 6617) return true;
    if (cp >= 6784 and cp <= 6793) return true;
    if (cp >= 6800 and cp <= 6809) return true;
    if (cp >= 6992 and cp <= 7001) return true;
    if (cp >= 7088 and cp <= 7097) return true;
    if (cp >= 7232 and cp <= 7241) return true;
    if (cp >= 7248 and cp <= 7257) return true;
    if (cp >= 42528 and cp <= 42537) return true;
    if (cp >= 43216 and cp <= 43225) return true;
    if (cp >= 43264 and cp <= 43273) return true;
    if (cp >= 43472 and cp <= 43481) return true;
    if (cp >= 43504 and cp <= 43513) return true;
    if (cp >= 43600 and cp <= 43609) return true;
    if (cp >= 44016 and cp <= 44025) return true;
    if (cp >= 65296 and cp <= 65305) return true;
    if (cp >= 66720 and cp <= 66729) return true;
    if (cp >= 68912 and cp <= 68921) return true;
    if (cp >= 69734 and cp <= 69743) return true;
    if (cp >= 69872 and cp <= 69881) return true;
    if (cp >= 69942 and cp <= 69951) return true;
    if (cp >= 70096 and cp <= 70105) return true;
    if (cp >= 70384 and cp <= 70393) return true;
    if (cp >= 70736 and cp <= 70745) return true;
    if (cp >= 70864 and cp <= 70873) return true;
    if (cp >= 71248 and cp <= 71257) return true;
    if (cp >= 71360 and cp <= 71369) return true;
    if (cp >= 71472 and cp <= 71481) return true;
    if (cp >= 71904 and cp <= 71913) return true;
    if (cp >= 72016 and cp <= 72025) return true;
    if (cp >= 72784 and cp <= 72793) return true;
    if (cp >= 73040 and cp <= 73049) return true;
    if (cp >= 73120 and cp <= 73129) return true;
    if (cp >= 92768 and cp <= 92777) return true;
    if (cp >= 93008 and cp <= 93017) return true;
    if (cp >= 120782 and cp <= 120831) return true;
    if (cp >= 123200 and cp <= 123209) return true;
    if (cp >= 123632 and cp <= 123641) return true;
    if (cp >= 125264 and cp <= 125273) return true;
    if (cp >= 130032 and cp <= 130041) return true;
    return false;
}