// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Digit code points.

lo: u21 = 178,
hi: u21 = 127242,

const Digit = @This();

pub fn isDigit(self: Digit, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 178 and cp <= 179) return true;
    if (cp == 185) return true;
    if (cp >= 4969 and cp <= 4977) return true;
    if (cp == 6618) return true;
    if (cp == 8304) return true;
    if (cp >= 8308 and cp <= 8313) return true;
    if (cp >= 8320 and cp <= 8329) return true;
    if (cp >= 9312 and cp <= 9320) return true;
    if (cp >= 9332 and cp <= 9340) return true;
    if (cp >= 9352 and cp <= 9360) return true;
    if (cp == 9450) return true;
    if (cp >= 9461 and cp <= 9469) return true;
    if (cp == 9471) return true;
    if (cp >= 10102 and cp <= 10110) return true;
    if (cp >= 10112 and cp <= 10120) return true;
    if (cp >= 10122 and cp <= 10130) return true;
    if (cp >= 68160 and cp <= 68163) return true;
    if (cp >= 69216 and cp <= 69224) return true;
    if (cp >= 69714 and cp <= 69722) return true;
    if (cp >= 127232 and cp <= 127242) return true;
    return false;
}