// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Deprecated code points.

lo: u21 = 329,
hi: u21 = 917505,

const Deprecated = @This();

pub fn isDeprecated(self: Deprecated, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 329) return true;
    if (cp == 1651) return true;
    if (cp == 3959) return true;
    if (cp == 3961) return true;
    if (cp >= 6051 and cp <= 6052) return true;
    if (cp >= 8298 and cp <= 8303) return true;
    if (cp == 9001) return true;
    if (cp == 9002) return true;
    if (cp == 917505) return true;
    return false;
}