// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Extender code points.

lo: u21 = 183,
hi: u21 = 125254,

const Extender = @This();

pub fn isExtender(self: Extender, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 183) return true;
    if (cp >= 720 and cp <= 721) return true;
    if (cp == 1600) return true;
    if (cp == 2042) return true;
    if (cp == 2901) return true;
    if (cp == 3654) return true;
    if (cp == 3782) return true;
    if (cp == 6154) return true;
    if (cp == 6211) return true;
    if (cp == 6823) return true;
    if (cp == 7222) return true;
    if (cp == 7291) return true;
    if (cp == 12293) return true;
    if (cp >= 12337 and cp <= 12341) return true;
    if (cp >= 12445 and cp <= 12446) return true;
    if (cp >= 12540 and cp <= 12542) return true;
    if (cp == 40981) return true;
    if (cp == 42508) return true;
    if (cp == 43471) return true;
    if (cp == 43494) return true;
    if (cp == 43632) return true;
    if (cp == 43741) return true;
    if (cp >= 43763 and cp <= 43764) return true;
    if (cp == 65392) return true;
    if (cp == 70493) return true;
    if (cp >= 71110 and cp <= 71112) return true;
    if (cp == 72344) return true;
    if (cp >= 92994 and cp <= 92995) return true;
    if (cp >= 94176 and cp <= 94177) return true;
    if (cp == 94179) return true;
    if (cp >= 123196 and cp <= 123197) return true;
    if (cp >= 125252 and cp <= 125254) return true;
    return false;
}