// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode HexDigit code points.

lo: u21 = 48,
hi: u21 = 65350,

const HexDigit = @This();

pub fn isHexDigit(self: HexDigit, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 48 and cp <= 57) return true;
    if (cp >= 65 and cp <= 70) return true;
    if (cp >= 97 and cp <= 102) return true;
    if (cp >= 65296 and cp <= 65305) return true;
    if (cp >= 65313 and cp <= 65318) return true;
    if (cp >= 65345 and cp <= 65350) return true;
    return false;
}