// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Hyphen code points.

lo: u21 = 45,
hi: u21 = 65381,

const Hyphen = @This();

pub fn isHyphen(self: Hyphen, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 45) return true;
    if (cp == 173) return true;
    if (cp == 1418) return true;
    if (cp == 6150) return true;
    if (cp >= 8208 and cp <= 8209) return true;
    if (cp == 11799) return true;
    if (cp == 12539) return true;
    if (cp == 65123) return true;
    if (cp == 65293) return true;
    if (cp == 65381) return true;
    return false;
}