// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode IDSBinaryOperator code points.

lo: u21 = 12272,
hi: u21 = 12283,

const IDSBinaryOperator = @This();

pub fn isIDSBinaryOperator(self: IDSBinaryOperator, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 12272 and cp <= 12273) return true;
    if (cp >= 12276 and cp <= 12283) return true;
    return false;
}