// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode LogicalOrderException code points.

lo: u21 = 3648,
hi: u21 = 43708,

const LogicalOrderException = @This();

pub fn isLogicalOrderException(self: LogicalOrderException, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 3648 and cp <= 3652) return true;
    if (cp >= 3776 and cp <= 3780) return true;
    if (cp >= 6581 and cp <= 6583) return true;
    if (cp == 6586) return true;
    if (cp >= 43701 and cp <= 43702) return true;
    if (cp == 43705) return true;
    if (cp >= 43707 and cp <= 43708) return true;
    return false;
}