// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode NoncharacterCodePoint code points.

lo: u21 = 64976,
hi: u21 = 1114111,

const NoncharacterCodePoint = @This();

pub fn isNoncharacterCodePoint(self: NoncharacterCodePoint, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 64976 and cp <= 65007) return true;
    if (cp >= 65534 and cp <= 65535) return true;
    if (cp >= 131070 and cp <= 131071) return true;
    if (cp >= 196606 and cp <= 196607) return true;
    if (cp >= 262142 and cp <= 262143) return true;
    if (cp >= 327678 and cp <= 327679) return true;
    if (cp >= 393214 and cp <= 393215) return true;
    if (cp >= 458750 and cp <= 458751) return true;
    if (cp >= 524286 and cp <= 524287) return true;
    if (cp >= 589822 and cp <= 589823) return true;
    if (cp >= 655358 and cp <= 655359) return true;
    if (cp >= 720894 and cp <= 720895) return true;
    if (cp >= 786430 and cp <= 786431) return true;
    if (cp >= 851966 and cp <= 851967) return true;
    if (cp >= 917502 and cp <= 917503) return true;
    if (cp >= 983038 and cp <= 983039) return true;
    if (cp >= 1048574 and cp <= 1048575) return true;
    if (cp >= 1114110 and cp <= 1114111) return true;
    return false;
}