// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode OtherIDStart code points.

lo: u21 = 6277,
hi: u21 = 12444,

const OtherIDStart = @This();

pub fn isOtherIDStart(self: OtherIDStart, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 6277 and cp <= 6278) return true;
    if (cp == 8472) return true;
    if (cp == 8494) return true;
    if (cp >= 12443 and cp <= 12444) return true;
    return false;
}