// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode OtherLowercase code points.

lo: u21 = 170,
hi: u21 = 43871,

const OtherLowercase = @This();

pub fn isOtherLowercase(self: OtherLowercase, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 170) return true;
    if (cp == 186) return true;
    if (cp >= 688 and cp <= 696) return true;
    if (cp >= 704 and cp <= 705) return true;
    if (cp >= 736 and cp <= 740) return true;
    if (cp == 837) return true;
    if (cp == 890) return true;
    if (cp >= 7468 and cp <= 7530) return true;
    if (cp == 7544) return true;
    if (cp >= 7579 and cp <= 7615) return true;
    if (cp == 8305) return true;
    if (cp == 8319) return true;
    if (cp >= 8336 and cp <= 8348) return true;
    if (cp >= 8560 and cp <= 8575) return true;
    if (cp >= 9424 and cp <= 9449) return true;
    if (cp >= 11388 and cp <= 11389) return true;
    if (cp >= 42652 and cp <= 42653) return true;
    if (cp == 42864) return true;
    if (cp >= 43000 and cp <= 43001) return true;
    if (cp >= 43868 and cp <= 43871) return true;
    return false;
}