// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode OtherUppercase code points.

lo: u21 = 8544,
hi: u21 = 127369,

const OtherUppercase = @This();

pub fn isOtherUppercase(self: OtherUppercase, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 8544 and cp <= 8559) return true;
    if (cp >= 9398 and cp <= 9423) return true;
    if (cp >= 127280 and cp <= 127305) return true;
    if (cp >= 127312 and cp <= 127337) return true;
    if (cp >= 127344 and cp <= 127369) return true;
    return false;
}