// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode QuotationMark code points.

lo: u21 = 34,
hi: u21 = 65379,

const QuotationMark = @This();

pub fn isQuotationMark(self: QuotationMark, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 34) return true;
    if (cp == 39) return true;
    if (cp == 171) return true;
    if (cp == 187) return true;
    if (cp == 8216) return true;
    if (cp == 8217) return true;
    if (cp == 8218) return true;
    if (cp >= 8219 and cp <= 8220) return true;
    if (cp == 8221) return true;
    if (cp == 8222) return true;
    if (cp == 8223) return true;
    if (cp == 8249) return true;
    if (cp == 8250) return true;
    if (cp == 11842) return true;
    if (cp == 12300) return true;
    if (cp == 12301) return true;
    if (cp == 12302) return true;
    if (cp == 12303) return true;
    if (cp == 12317) return true;
    if (cp >= 12318 and cp <= 12319) return true;
    if (cp == 65089) return true;
    if (cp == 65090) return true;
    if (cp == 65091) return true;
    if (cp == 65092) return true;
    if (cp == 65282) return true;
    if (cp == 65287) return true;
    if (cp == 65378) return true;
    if (cp == 65379) return true;
    return false;
}