// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode SoftDotted code points.

lo: u21 = 105,
hi: u21 = 120467,

const SoftDotted = @This();

pub fn isSoftDotted(self: SoftDotted, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 105 and cp <= 106) return true;
    if (cp == 303) return true;
    if (cp == 585) return true;
    if (cp == 616) return true;
    if (cp == 669) return true;
    if (cp == 690) return true;
    if (cp == 1011) return true;
    if (cp == 1110) return true;
    if (cp == 1112) return true;
    if (cp == 7522) return true;
    if (cp == 7574) return true;
    if (cp == 7588) return true;
    if (cp == 7592) return true;
    if (cp == 7725) return true;
    if (cp == 7883) return true;
    if (cp == 8305) return true;
    if (cp >= 8520 and cp <= 8521) return true;
    if (cp == 11388) return true;
    if (cp >= 119842 and cp <= 119843) return true;
    if (cp >= 119894 and cp <= 119895) return true;
    if (cp >= 119946 and cp <= 119947) return true;
    if (cp >= 119998 and cp <= 119999) return true;
    if (cp >= 120050 and cp <= 120051) return true;
    if (cp >= 120102 and cp <= 120103) return true;
    if (cp >= 120154 and cp <= 120155) return true;
    if (cp >= 120206 and cp <= 120207) return true;
    if (cp >= 120258 and cp <= 120259) return true;
    if (cp >= 120310 and cp <= 120311) return true;
    if (cp >= 120362 and cp <= 120363) return true;
    if (cp >= 120414 and cp <= 120415) return true;
    if (cp >= 120466 and cp <= 120467) return true;
    return false;
}