// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode TerminalPunctuation code points.

lo: u21 = 33,
hi: u21 = 121482,

const TerminalPunctuation = @This();

pub fn isTerminalPunctuation(self: TerminalPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 33) return true;
    if (cp == 44) return true;
    if (cp == 46) return true;
    if (cp >= 58 and cp <= 59) return true;
    if (cp == 63) return true;
    if (cp == 894) return true;
    if (cp == 903) return true;
    if (cp == 1417) return true;
    if (cp == 1475) return true;
    if (cp == 1548) return true;
    if (cp == 1563) return true;
    if (cp >= 1566 and cp <= 1567) return true;
    if (cp == 1748) return true;
    if (cp >= 1792 and cp <= 1802) return true;
    if (cp == 1804) return true;
    if (cp >= 2040 and cp <= 2041) return true;
    if (cp >= 2096 and cp <= 2110) return true;
    if (cp == 2142) return true;
    if (cp >= 2404 and cp <= 2405) return true;
    if (cp >= 3674 and cp <= 3675) return true;
    if (cp == 3848) return true;
    if (cp >= 3853 and cp <= 3858) return true;
    if (cp >= 4170 and cp <= 4171) return true;
    if (cp >= 4961 and cp <= 4968) return true;
    if (cp == 5742) return true;
    if (cp >= 5867 and cp <= 5869) return true;
    if (cp >= 5941 and cp <= 5942) return true;
    if (cp >= 6100 and cp <= 6102) return true;
    if (cp == 6106) return true;
    if (cp >= 6146 and cp <= 6149) return true;
    if (cp >= 6152 and cp <= 6153) return true;
    if (cp >= 6468 and cp <= 6469) return true;
    if (cp >= 6824 and cp <= 6827) return true;
    if (cp >= 7002 and cp <= 7003) return true;
    if (cp >= 7005 and cp <= 7007) return true;
    if (cp >= 7227 and cp <= 7231) return true;
    if (cp >= 7294 and cp <= 7295) return true;
    if (cp >= 8252 and cp <= 8253) return true;
    if (cp >= 8263 and cp <= 8265) return true;
    if (cp == 11822) return true;
    if (cp == 11836) return true;
    if (cp == 11841) return true;
    if (cp == 11852) return true;
    if (cp >= 11854 and cp <= 11855) return true;
    if (cp >= 12289 and cp <= 12290) return true;
    if (cp >= 42238 and cp <= 42239) return true;
    if (cp >= 42509 and cp <= 42511) return true;
    if (cp >= 42739 and cp <= 42743) return true;
    if (cp >= 43126 and cp <= 43127) return true;
    if (cp >= 43214 and cp <= 43215) return true;
    if (cp == 43311) return true;
    if (cp >= 43463 and cp <= 43465) return true;
    if (cp >= 43613 and cp <= 43615) return true;
    if (cp == 43743) return true;
    if (cp >= 43760 and cp <= 43761) return true;
    if (cp == 44011) return true;
    if (cp >= 65104 and cp <= 65106) return true;
    if (cp >= 65108 and cp <= 65111) return true;
    if (cp == 65281) return true;
    if (cp == 65292) return true;
    if (cp == 65294) return true;
    if (cp >= 65306 and cp <= 65307) return true;
    if (cp == 65311) return true;
    if (cp == 65377) return true;
    if (cp == 65380) return true;
    if (cp == 66463) return true;
    if (cp == 66512) return true;
    if (cp == 67671) return true;
    if (cp == 67871) return true;
    if (cp >= 68182 and cp <= 68183) return true;
    if (cp >= 68336 and cp <= 68341) return true;
    if (cp >= 68410 and cp <= 68415) return true;
    if (cp >= 68505 and cp <= 68508) return true;
    if (cp >= 69461 and cp <= 69465) return true;
    if (cp >= 69703 and cp <= 69709) return true;
    if (cp >= 69822 and cp <= 69825) return true;
    if (cp >= 69953 and cp <= 69955) return true;
    if (cp >= 70085 and cp <= 70086) return true;
    if (cp == 70093) return true;
    if (cp >= 70110 and cp <= 70111) return true;
    if (cp >= 70200 and cp <= 70204) return true;
    if (cp == 70313) return true;
    if (cp >= 70731 and cp <= 70733) return true;
    if (cp >= 70746 and cp <= 70747) return true;
    if (cp >= 71106 and cp <= 71109) return true;
    if (cp >= 71113 and cp <= 71127) return true;
    if (cp >= 71233 and cp <= 71234) return true;
    if (cp >= 71484 and cp <= 71486) return true;
    if (cp == 72004) return true;
    if (cp == 72006) return true;
    if (cp >= 72258 and cp <= 72259) return true;
    if (cp >= 72347 and cp <= 72348) return true;
    if (cp >= 72353 and cp <= 72354) return true;
    if (cp >= 72769 and cp <= 72771) return true;
    if (cp == 72817) return true;
    if (cp >= 73463 and cp <= 73464) return true;
    if (cp >= 74864 and cp <= 74868) return true;
    if (cp >= 92782 and cp <= 92783) return true;
    if (cp == 92917) return true;
    if (cp >= 92983 and cp <= 92985) return true;
    if (cp == 92996) return true;
    if (cp >= 93847 and cp <= 93848) return true;
    if (cp == 113823) return true;
    if (cp >= 121479 and cp <= 121482) return true;
    return false;
}