// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode UnifiedIdeograph code points.

lo: u21 = 13312,
hi: u21 = 201546,

const UnifiedIdeograph = @This();

pub fn isUnifiedIdeograph(self: UnifiedIdeograph, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 13312 and cp <= 19903) return true;
    if (cp >= 19968 and cp <= 40956) return true;
    if (cp >= 64014 and cp <= 64015) return true;
    if (cp == 64017) return true;
    if (cp >= 64019 and cp <= 64020) return true;
    if (cp == 64031) return true;
    if (cp == 64033) return true;
    if (cp >= 64035 and cp <= 64036) return true;
    if (cp >= 64039 and cp <= 64041) return true;
    if (cp >= 131072 and cp <= 173789) return true;
    if (cp >= 173824 and cp <= 177972) return true;
    if (cp >= 177984 and cp <= 178205) return true;
    if (cp >= 178208 and cp <= 183969) return true;
    if (cp >= 183984 and cp <= 191456) return true;
    if (cp >= 196608 and cp <= 201546) return true;
    return false;
}