// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode VariationSelector code points.

lo: u21 = 6155,
hi: u21 = 917999,

const VariationSelector = @This();

pub fn isVariationSelector(self: VariationSelector, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp >= 6155 and cp <= 6157) return true;
    if (cp >= 65024 and cp <= 65039) return true;
    if (cp >= 917760 and cp <= 917999) return true;
    return false;
}