// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Fullwidth code points.

lo: u21 = 12288,
hi: u21 = 65510,

const Fullwidth = @This();

pub fn isFullwidth(self: Fullwidth, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 12288) return true;
    if (cp >= 65281 and cp <= 65283) return true;
    if (cp == 65284) return true;
    if (cp >= 65285 and cp <= 65287) return true;
    if (cp == 65288) return true;
    if (cp == 65289) return true;
    if (cp == 65290) return true;
    if (cp == 65291) return true;
    if (cp == 65292) return true;
    if (cp == 65293) return true;
    if (cp >= 65294 and cp <= 65295) return true;
    if (cp >= 65296 and cp <= 65305) return true;
    if (cp >= 65306 and cp <= 65307) return true;
    if (cp >= 65308 and cp <= 65310) return true;
    if (cp >= 65311 and cp <= 65312) return true;
    if (cp >= 65313 and cp <= 65338) return true;
    if (cp == 65339) return true;
    if (cp == 65340) return true;
    if (cp == 65341) return true;
    if (cp == 65342) return true;
    if (cp == 65343) return true;
    if (cp == 65344) return true;
    if (cp >= 65345 and cp <= 65370) return true;
    if (cp == 65371) return true;
    if (cp == 65372) return true;
    if (cp == 65373) return true;
    if (cp == 65374) return true;
    if (cp == 65375) return true;
    if (cp == 65376) return true;
    if (cp >= 65504 and cp <= 65505) return true;
    if (cp == 65506) return true;
    if (cp == 65507) return true;
    if (cp == 65508) return true;
    if (cp >= 65509 and cp <= 65510) return true;
    return false;
}