// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Halfwidth code points.

lo: u21 = 8361,
hi: u21 = 65518,

const Halfwidth = @This();

pub fn isHalfwidth(self: Halfwidth, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 8361) return true;
    if (cp == 65377) return true;
    if (cp == 65378) return true;
    if (cp == 65379) return true;
    if (cp >= 65380 and cp <= 65381) return true;
    if (cp >= 65382 and cp <= 65391) return true;
    if (cp == 65392) return true;
    if (cp >= 65393 and cp <= 65437) return true;
    if (cp >= 65438 and cp <= 65439) return true;
    if (cp >= 65440 and cp <= 65470) return true;
    if (cp >= 65474 and cp <= 65479) return true;
    if (cp >= 65482 and cp <= 65487) return true;
    if (cp >= 65490 and cp <= 65495) return true;
    if (cp >= 65498 and cp <= 65500) return true;
    if (cp == 65512) return true;
    if (cp >= 65513 and cp <= 65516) return true;
    if (cp >= 65517 and cp <= 65518) return true;
    return false;
}