// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Narrow code points.

lo: u21 = 32,
hi: u21 = 10630,

const Narrow = @This();

pub fn isNarrow(self: Narrow, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 32) return true;
    if (cp >= 33 and cp <= 35) return true;
    if (cp == 36) return true;
    if (cp >= 37 and cp <= 39) return true;
    if (cp == 40) return true;
    if (cp == 41) return true;
    if (cp == 42) return true;
    if (cp == 43) return true;
    if (cp == 44) return true;
    if (cp == 45) return true;
    if (cp >= 46 and cp <= 47) return true;
    if (cp >= 48 and cp <= 57) return true;
    if (cp >= 58 and cp <= 59) return true;
    if (cp >= 60 and cp <= 62) return true;
    if (cp >= 63 and cp <= 64) return true;
    if (cp >= 65 and cp <= 90) return true;
    if (cp == 91) return true;
    if (cp == 92) return true;
    if (cp == 93) return true;
    if (cp == 94) return true;
    if (cp == 95) return true;
    if (cp == 96) return true;
    if (cp >= 97 and cp <= 122) return true;
    if (cp == 123) return true;
    if (cp == 124) return true;
    if (cp == 125) return true;
    if (cp == 126) return true;
    if (cp >= 162 and cp <= 163) return true;
    if (cp == 165) return true;
    if (cp == 166) return true;
    if (cp == 172) return true;
    if (cp == 175) return true;
    if (cp == 10214) return true;
    if (cp == 10215) return true;
    if (cp == 10216) return true;
    if (cp == 10217) return true;
    if (cp == 10218) return true;
    if (cp == 10219) return true;
    if (cp == 10220) return true;
    if (cp == 10221) return true;
    if (cp == 10629) return true;
    if (cp == 10630) return true;
    return false;
}