// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode FinalPunctuation code points.

lo: u21 = 187,
hi: u21 = 11809,

const FinalPunctuation = @This();

pub fn isFinalPunctuation(self: FinalPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    if (cp == 187) return true;
    if (cp == 8217) return true;
    if (cp == 8221) return true;
    if (cp == 8250) return true;
    if (cp == 11779) return true;
    if (cp == 11781) return true;
    if (cp == 11786) return true;
    if (cp == 11789) return true;
    if (cp == 11805) return true;
    if (cp == 11809) return true;
    return false;
}